### ISSUE TITLE
Update Meetup.com template for discussions?

### ISSUE THREAD

**Issue by jszwedko** [sfbrigade/Infrastructure-Team#24]
Currently the meetup.com event template links to the IRC channel on Freenode which is not very active (I checked tonight and there were two people including myself). Should we link to Slack (making our org public?) or maybe Twitter with a given #hashtag?

cc/ @vedrana15

**Comment by jszwedko** [comment]
It also links to the Google group which is a little active -- I didn't even know it existed. I personally think fragmenting the discussion mediums isn't ideal with an organization this size (if we were 1000s of members, letting them gravitate to their preferred medium makes more sense as all would be active), but I'm curious how others feel.

**Comment by afomi** [comment]
Given the low usage of the IRC channel, I'd be okay with closing it down. Keeping the IRC channel open is an implicit commitment going largely unfulfilled.

:+1: to linking to Slack and Twitter via the Meetup page

For the Google Group, there seems to be a fair amount of traffic.  Reviewing the content since 1/1/2014, there are a few categories of posts:

#### Types of Content
- hospitality - greetings, welcomes, general chit chat
- projects - announcements, status updates, help requests
- issues - problems
- community - questions, advice, help requests, events, 
- industry news - events, job opps, grant funding opportunities
- spam/off-topic

I'd be interested in designers to take a pass here too. My thinking is all these items (the data involved) live in a place that is not the Google Group, and requires a bit of coordination to get it to the right interface. Thus, maybe these areas for improvement become projects over time.

Nevertheless, how could this work if the Google Group went away?
- hospitality - greetings, welcomes, general chit chat < SLACK
- projects - announcements, status updates, help requests < SLACK PROJECT CHANNELS
- issues - problems < GITHUB
- community - questions, advice, help requests, events < SLACK
- industry news - events, job opps, grant funding opportunities < SLACK
- spam/off-topic 
- but no email interface... which is exclusive.

### Things to highlight

And here are some things I saw in the Google Group that I'd like to see more of:
- Cross-Brigade and cross-regional posting - Sacramento, Denver, Suburbs
- Specific help-requests (I'm a _____, looking for a ______ for _________)
- Project TImelines, Histories, Statuses - so I have some idea how to contribute

**Comment by jszwedko** [comment]
Wow, thank you for surveying! I think your mapping is accurate.

I agree that the lack of an e-mail interface for Slack is exclusionary -- we could enable the XMPP and IRC gateways to make it more client agnostic at least (see https://slack.zendesk.com/hc/en-us/articles/201727913-Connecting-to-Slack-over-IRC-and-XMPP)

For your highlights:
- Specific help-requests (I'm a _____, looking for a ______ for _________) -- I think make a lot of sense on Slack
- Project TImelines, Histories, Statuses - so I have some idea how to contribute -- I like this on Github, but I could see arguments for other mediums
- Cross-Brigade and cross-regional posting - Sacramento, Denver, Suburbs -- Twitter?

**Comment by vedrana15** [comment]
I agree about keeping the chat only on slack - having to many options can be overwhelming.

**Comment by jszwedko** [comment]
Closing this as we have a link to Slack on the meetup now and the IRC channel gets very little traffic as-is.
